### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by SamuelMarks** [franzeal/ngx-formly-designer#1]
Tony Franzese,

Your project looks interesting! - Little more U/X optimisation and drag-drop of components, then it'd be perfect.

What are your plans with this project? - Keen to collaborate on these two features + Angular 6 + latest formly upgrade?

**Comment by franzeal** [comment]
My immediate plan is to update to Angular 6, the latest formly, and restructure the project to use the CLI's library build process.  The make-current branch is the start of that effort, which needs debug concerning field groups / their wrappers (hence why I've stalled going on two months now).

[ngx-formly-tabs](https://github.com/franzeal/ngx-formly-tabs) was my test run for doing that.  The approach I'm taking here is to first get the existing application updated (Angular and formly) before restructuring it to use the CLI structure to build libraries similar to that test run.

I'd be happy to collaborate.

**Comment by SamuelMarks** [comment]
@franzeal Okay, well in that case I've contributed a PR => https://github.com/franzeal/ng-formly-designer/pull/3

- Generated new scaffold for latest Angular 6;
- migrated syntax;
- replaced lodash—except two of its functions—with own utils

Want to remove JQuery next, as well as the `set` and `unset` function usage of lodash. Maybe you can look at it?

**Comment by franzeal** [comment]
I'm not able to build the PR, can you?  Just curious.

The last effort I made on this was more recent than I thought and hadn't been put into github.  That effort included the restructuring into separate app (demo) and lib projects with Angular 6.  I apologize for not realizing that sooner.

I've pushed that to make-current-lib-restructure.  You're welcome to check that out and reincorporate your changes, but my first priority is to fix the broken behavior that I ran into when I did the restructure and upgrade.

**Comment by SamuelMarks** [comment]
Arghhh. Yeah okay I'll reincorporate my changes.

PS: Nah it was a WiP PR, if you just add lodash and JQuery dependencies it should work+compile just fine.

**Comment by SamuelMarks** [comment]
Done: https://github.com/franzeal/ng-formly-designer/pull/4

**Comment by franzeal** [comment]
I've pushed commits to address the field group / wrappers issues that were of most concern to me.  I still have a todo to move reserved wrappers into the designer config.

Removed utils from the lib's exports; reverted the demo to use lodash.

The cloneDeep replacement doesn't seem adequate; adding an input then a field group would cause an error within Angular's reactive forms.

**Comment by SamuelMarks** [comment]
@franzeal Good to see the Angular 12 upgrade
