### ISSUE TITLE
Select - Adding Options Dynamically

### ISSUE THREAD

**Issue by Wiljanneman** [franzeal/ngx-formly-designer#10]
https://franzeal.github.io/ngx-formly-designer/

WIth regards to the Select type...I see a repeatSection type in the designer config:
`                {
                    key: 'templateOptions.options',
                    type: 'repeatSection',
                    templateOptions: {
                        canAdd: true,
                        canRemove: true
                    },
                    fieldArray: {
                        className: 'ml-3',
                        fieldGroup: [
                            {
                                key: 'label',
                                type: 'input',
                                templateOptions: {
                                    label: 'label'
                                }
                            },
                            {
                                key: 'value',
                                type: 'input',
                                templateOptions: {
                                    label: 'value'
                                }
                            }
                        ]
                    }
                },`

However, I don't see a repeat section in the demo or the repo I downloaded.  Forgive me if I'm missing something somewhere.  I'm trying to figure out how one would dynamically add options to a Select or Radio Button Group.
![fieldarraytype](https://user-images.githubusercontent.com/17082974/52809810-ca14c880-3099-11e9-8f85-a319079c8136.PNG)

Thanks in advance!

**Comment by franzeal** [comment]
It's not you, it's broke.  I'll work to address it.
