### ISSUE TITLE
fieldGroupClassName cannot be set in a fieldGroup

### ISSUE THREAD

**Issue by whvneo** [franzeal/ngx-formly-designer#11]
Hello, 

I played a bit with your designer and have an issue with fieldGroups.

In the demo I cannot set the fieldGroupClassName, is that a mistake from the demo or is this feature just missing?

cheers
Andreas

**Comment by franzeal** [comment]
Missing feature.  I'll work to get it added.

**Comment by whvneo** [comment]
Hello, 

thanks for fixing it so amazingly fast.

Cheers
