### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by weilies** [franzeal/ngx-formly-designer#23]
Good day support, 

The demo is down. https://franzeal.github.io/ngx-formly-designer
![image](https://user-images.githubusercontent.com/484828/134438616-b8c7691a-c3c2-488f-b755-b49c8fd9951d.png)

would u be able to provide a stackblitz demo? :)

**Comment by michaelbuller** [comment]
![Screenshot_20210922-203526_Chrome](https://user-images.githubusercontent.com/901172/134439562-e14dab41-1020-429f-a433-16174c751bf6.jpg)

**Comment by weilies** [comment]
Thanks! i guess it's Github temp hiccup
