### ISSUE TITLE
expressionProperties - Required Expression

### ISSUE THREAD

**Issue by Wiljanneman** [franzeal/ngx-formly-designer#9]
Hi 

Is there a way one can create an expression property for toggling required fields?

`                {
                    key: 'hideExpression',
                    type: 'input',
                    templateOptions: {
                        label: 'Hide Expression'
                    }
                },
`
Maybe something similar to what I used for the hide expression.

**Comment by franzeal** [comment]
I think the impediment to doing that with simple fieldGroup (expressionProperties) + input (templateOptions.required) is the latter's path.  ngx-formly will break templateOptions.required into an object with a property when in this case you'd need the key preserved as is.

An approach that should work is to create a custom type that would interact with that part of the model:
```TypeScript
{
    type: 'expressionProperty',
    templateOptions: {
        property: 'templateOptions.required'
    }
}
`
